pipeline {
    agent any

    stages {
        stage("Build & making tar file") {
            steps {
                sh "cd demo-frontend && npm install && npm run build"
            }
        }
        stage('making tar file') {
            steps {
                sh "tar -cvf npmtar.1.1.1.tar build"
            }
        }
        stage('pushing to nexus reo') {
            steps {
                sh 'curl -v -u maven:12345 --upload-file npmtar.1.1.1.tar "https://your-nexus-repo-url/repository/your-repository-name/npmtar.1.1.1.tar"'
            }
        }
    }
}
